---
format: html
editor: source
---

# Base de datos {#databases}

La base de datos se encuentra disponible para libre descarga en el repositorio github del proyecto.

- [Repositorio del proyecto LISA](https://github.com/lisa-coes)

- [Repositorio de este documento](https://github.com/lisa-coes/cais-book)

- [Link directo de descarga de la base de datos](https://github.com/lisa-coes/cais-book/raw/refs/heads/main/input/data/original/cais.RData)

## Algunas informaciones generales

La base de datos cuenta con 150 respuestas, que corresponden a la totalidad de personas que aceptaron participar en la investigación.

Sin embargo, el desglose aproximado de respuestas completas es el siguiente:

- Cantidad de personas que respondieron la encuesta completa: 50 

- Cantidad de personas que respondieron el 75% de la encuesta: 97

- Cantidad de personas que respondieron el 50% de la encuesta: 106

- Cantidad de personas que respondieron el 25% de la encuesta: 147

- Cantidad de personas que respondieron el módulo opcional sobre aceleración académica: 45