project:
  type: book
  output-dir: docs

book:
  title: "Manual Metodológico CAIS"
  author: "Equipo LISA"
  date: 29/11/2024
  reader-mode: true
  page-footer:
    left: |
      Proyecto Mini-COES "Prácticas, Creencias y Conocimiento en Ciencia Abierta: Propuestas para las ciencias sociales".

    right: |
      Este libro se construyó con <a href="https://quarto.org/">Quarto</a>.
  page-navigation: true
  cover-image: edumer.png
  favicon: edumer.png
  repo-url: https://github.com/lisa-coes/cais-book
  repo-branch: main
  chapters:
    - index.qmd
    - 01-antecedents.qmd
    - 02-database.qmd
    - 03-codebook.qmd
  search:
    location: sidebar
    type: textbox
  sidebar:
    search: true
    style: docked
    pinned: false


format:
  html:
    theme:
      - cosmo
      - edumer.scss
    code-link: true

editor: visual
lang: es

bibliography: "input/bib/manual-metod.bib"
csl: "input/bib/apa6.csl"

